wallpaper {
    monitor = DP-3
    path = /home/marcel/Pictures/Wallpaper/Horizontal/bmw-e30-dtm-side.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/marcel/Pictures/Wallpaper/Horizontal/bmw-e30-dtm-front.jpg
    fit_mode = cover
}

splash = false
